"""empty message

Revision ID: 8f9774b63b78
Revises: 9e9c4cb2b97b
Create Date: 2021-12-30 15:18:01.600582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9774b63b78'
down_revision = '9e9c4cb2b97b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_name'), 'achievements', ['name'], unique=True)
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_achievement', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_achievement'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'secondName',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'firstName',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_achievements_name'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
