"""'Upgrade'

Revision ID: 9e9c4cb2b97b
Revises: 
Create Date: 2021-11-13 19:15:19.386858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9c4cb2b97b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_index(op.f('ix_users_firstName'), 'users', ['firstName'], unique=False)
    op.create_index(op.f('ix_users_secondName'), 'users', ['secondName'], unique=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_secondName'), table_name='users')
    op.drop_index(op.f('ix_users_firstName'), table_name='users')
    op.alter_column('users', 'secondName',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'firstName',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
